# In this notebook we are going to cover some of the most fundemental concepts of tensors using Tensorflow

## More specifically, we are going to cover:
- Introducing to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors & NumPy
- Using @tf.function (a way to speed up your regular Python functions)
- Using GPUs with TensorFlow (or TPUs)
- Exercise to try for myself

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2023-12-15 14:17:27.112396: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-15 14:17:27.196900: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-15 14:17:27.693980: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-15 14:17:27.694100: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-15 14:17:27.805965: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

2.15.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensions of the tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimensions of my vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# create another matrix
matrix_2 = tf.constant([[10.,7.],
                        [3.,2.],
                        [8.,9.]], dtype=tf.float16) #specify the data type with dtype parameter
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
matrix_2.ndim

2

In [10]:
# creating a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                        [[13, 14, 15],
                         [16, 17 ,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What i have created so far
- Scalar: a single number
- Vector: a number with direction
- Matrix: a 2-dimensional array of numbers
- Tensor: a n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with `tf.variable`

In [12]:
# Create the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10, 7])
unchageable_tensor = tf.constant([10, 7])
changeable_tensor, unchageable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# lets try change one of the elements in our changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

🔑 **Note:** Rarely in practice will you need to decide wheter to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [14]:
# Create 2 ramdons tensors (but the same)
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order in a tensor

In [15]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order does not effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
#shuffle my no-shufled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

🛠️ **Exercise:** Practice on random seed generation and write 5 random tensors and shuffle them.

#### Global Seed

In [16]:
tf.random.set_seed(42)

for i in range(1, 6):
    tensor = tf.random.uniform(shape=[3])
    shuffled_tensor = tf.random.shuffle(tensor)
    print(f"Mix Tensor {i}: {shuffled_tensor.numpy()}")


Mix Tensor 1: [0.3528825  0.6645621  0.44100678]
Mix Tensor 2: [0.01738465 0.62854624 0.7413678 ]
Mix Tensor 3: [0.803156   0.37054038 0.49777734]
Mix Tensor 4: [0.43555546 0.49674678 0.52486527]
Mix Tensor 5: [0.81674874 0.2046014  0.82478166]


All shuffled tensors will be reproducible across script executions. The shuffle sequence will be the same every time you run the script. This is because the global seed sets a common starting point for all random operations, ensuring consistency.

#### Operation-Level Seed

In [17]:
for i in range(1, 6):
    tensor = tf.random.uniform(shape=[3], seed=1)
    shuffled_tensor = tf.random.shuffle(tensor)
    print(f"Mix Tensor {i}: {shuffled_tensor.numpy()}")

Mix Tensor 1: [0.63992536 0.81787777 0.15012848]
Mix Tensor 2: [0.20244026 0.4828781  0.22027123]
Mix Tensor 3: [0.06012475 0.02529657 0.01177216]
Mix Tensor 4: [0.8162794  0.95071614 0.26013935]
Mix Tensor 5: [0.9129821  0.33574915 0.61781967]


The shuffle of each tensor depends on the specific seed passed to the operation. Without a global seed, the results will not be reproducible across different script executions. This is because the operation-level seed controls the randomness of that particular operation, but without a global reference point, each run starts with a different internal state.

#### Global Seed and Operation-Level Seed 

In [18]:
tf.random.set_seed(42)

for i in range(1, 6):
    tensor = tf.random.uniform(shape=[3], seed=1)
    shuffled_tensor = tf.random.shuffle(tensor)
    print(f"Mix Tensor {i}: {shuffled_tensor.numpy()}")

Mix Tensor 1: [0.63992536 0.81787777 0.15012848]
Mix Tensor 2: [0.22027123 0.4828781  0.20244026]
Mix Tensor 3: [0.06012475 0.02529657 0.01177216]
Mix Tensor 4: [0.95071614 0.26013935 0.8162794 ]
Mix Tensor 5: [0.61781967 0.33574915 0.9129821 ]


The global seed ensures reproducibility across executions, while the operation-level seed controls the specific shuffle in each operation. This combination allows for consistent, repeatable results across script runs (thanks to the global seed) but with controlled variation in each operation (due to the operation-level seed).

### Other ways to make tensors

In [19]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
# Create a tensor of all zeroes
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between Numpy arrays and TensorFlow tensors can be run on a GPU (much faster for numerical computing)

In [21]:
# Turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) capital for matrix or tensor
# y = tf.constant(vector) non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors
- **Shape:** The length of each of the dimensions of the tensor `tensor.shape`

- **Rank:** The number of tensor dimension `tensor.ndim`

- **Axis or dimension:** A particular dimension of a tensor `tensor[0]` `tensor[:, 1]`

- **Size:** The total number of items in the tensor `tf.size(tensor)`

In [23]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [25]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in my tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in my tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in my tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in my tensor:  120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [26]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[2, 3],
                             [10, 7]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [29]:
# Get the last item of each row of my rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7], dtype=int32)>

In [30]:
# Add in extra dimension to the rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 2],
        [ 3]],

       [[10],
        [ 7]]], dtype=int32)>

In [31]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 2],
        [ 3]],

       [[10],
        [ 7]]], dtype=int32)>

In [32]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[ 2,  3],
        [10,  7]]], dtype=int32)>

### Manipulating tensors (tensor operations)
**Basic operations** `+`,`-`,`*`,`/`

In [33]:
# You can add values to a tensor using the addittion operator
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [34]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [35]:
# Substraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [36]:
# We can use tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [37]:
# Original tensor is unchaged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.
1. The inner dimensions must match
2. The resulting matrix has te shape of the inner dimensions

You can perform matrix multplication using:
- `tf.matmul()`
- `tf.tensordot()`

In [38]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [39]:
# Matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [40]:
# Create a tensor (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[9, 8],
                 [7, 6],
                 [5, 4]])

📖 **Resource:** Infor and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

- The number of columns of the 1st matrix must equal the number of rows of the 2nd matrix.
- And the result will have the same number of rows as the 1st matrix, and the same number of columns as the 2nd matrix.

In [41]:
# Lets change the shape of Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 8, 7],
       [6, 5, 4]], dtype=int32)>

In [42]:
X.shape, tf.reshape(Y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [43]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[21, 18, 15],
       [51, 44, 37],
       [81, 70, 59]], dtype=int32)>

In [44]:
# Can do the same with transpose (switch the axies)
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

Generally, when performing matrix multiplication on two tensros and of the axes does not line up, you will transponse one of the tensors in order to satisfy the matrix multiplication rules

### Chaging the datatype of a tensor

In [45]:
# Create a new tensor with default dtype (float32)
B = tf.constant([1.7, 7.4])
C = tf.constant([7, 10])
B.dtype, C.dtype

(tf.float32, tf.int32)

In [46]:
# Change from float32 to float16 (reduced precission)
D = tf.cast(B, tf.float16)
D.dtype

tf.float16

In [47]:
# Change from int32 to float32
E = tf.cast(C, tf.float32)

### Aggregatin tensors

Aggregatin tensors = condensing them from multiple values down to a smaller amount of values.

In [48]:
# Get the absolute values
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go trough the following forms of aggregation:
- Get the minimum
- Get the maximum
- Get the mean
- Get the sum 

In [52]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([43, 24, 38, 53, 79,  8, 98, 70,  0, 38, 26, 99, 55, 92, 29, 87, 80,
       84, 63,  2, 70, 66, 20,  7, 92, 54, 94, 61,  5, 66, 18, 22, 91, 99,
       36, 22, 31, 63, 29, 23, 10, 82, 34, 10, 28, 41,  2, 18,  8, 13])>

In [53]:
minimum = tf.reduce_min(E)
maximum = tf.reduce_max(E)
mean = tf.reduce_mean(E)
sum = tf.reduce_sum(E)

print("Minimum: ", minimum.numpy())
print("Maximum: ", maximum.numpy())
print("Mean: ", mean.numpy())
print("Sum: ",sum.numpy())

Minimum:  0
Maximum:  99
Mean:  45
Sum:  2283


🛠️ **Excercise** Find the variance and standard deviation of our `E` tensor

In [55]:
# Change the dtype to float32

F = tf.cast(E, tf.float16)

variance = tf.math.reduce_variance(F)
std_deviation = tf.math.reduce_std(F)

print("Variance: ", variance.numpy())
print("Std devation: ", std_deviation.numpy())

Variance:  972.0
Std devation:  31.17


### Find the positional maximun and minimum

In [57]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [58]:
# Find the positional maximun
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [59]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [60]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [61]:
# Index on our minimum value position
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [91]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [1, 1, 1, 1, 50]))
G.shape

TensorShape([1, 1, 1, 1, 50])

In [92]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

### One-hot encoding tensors

In [93]:
# Create a list of indices
colours = [0, 1, 2, 3] # red, green, blue, purple

#One-hot encode our list of indices
tf.one_hot(colours, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [95]:
# Specify custom values for one hot encoding
tf.one_hot(colours, depth=4, on_value="love deep learning", off_value="also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'love deep learning', b'also like to dance',
        b'also like to dance', b'also like to dance'],
       [b'also like to dance', b'love deep learning',
        b'also like to dance', b'also like to dance'],
       [b'also like to dance', b'also like to dance',
        b'love deep learning', b'also like to dance'],
       [b'also like to dance', b'also like to dance',
        b'also like to dance', b'love deep learning']], dtype=object)>

### Squaring, log, square root

In [105]:
# Create a tensor
tf.random.set_seed(42)
A = tf.constant(tf.random.uniform(shape=[3,5]))
A

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041],
       [0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
       [0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ]],
      dtype=float32)>

In [108]:
square = tf.square(A)
log = tf.math.log(A)
square_root = tf.sqrt(A)

print("Squaring: ", square.numpy())
print("Natural log", log.numpy())
print("Square: ", square_root.numpy())

Squaring:  [[0.4416428  0.19448698 0.12452606 0.21574403 0.00113302]
 [0.46877623 0.54777384 0.7611594  0.05122361 0.04981684]
 [0.09634077 0.52176905 0.01773882 0.300374   0.33017528]]
Natural log [[-0.40862694 -0.818695   -1.0416201  -0.7668313  -3.3914328 ]
 [-0.37881485 -0.3009464  -0.13645622 -1.4857773  -1.4997011 ]
 [-1.1699319  -0.32526514 -2.0159998  -0.6013634  -0.5540658 ]]
Square:  [[0.81520677 0.6640834  0.59403914 0.6815296  0.18346775]
 [0.8274493  0.8603008  0.9340474  0.4757377  0.47243714]
 [0.55712485 0.8499034  0.36494818 0.74031335 0.7580296 ]]
